### ISSUE TITLE
Connection refused: using container assigned IP ?

### ISSUE THREAD

**Issue by ogdabou** [adi90x/rancher-active-proxy#3]
Hi,

First, thank you for this catalog entry which is VERY appealing for me (I'm a newcomer in the HTTPS world, which looks like hell to me).   

**Environment**  
I am running one VPS instance at OVH, and trying rancher-active-proxy on single host after trying for a rancher environment with multi-host.
- **docker**: v1.10.3
- **rancher**: v1.1.4, I'm using docker-compose v1, so the syntaxe is very close the one posted on this repository
- Using debian 8 original kernel (not ovh-custom)

**Reproduce**
- Setup a new host
- Start rancher-active-proxy
- Start a standalone container SimpleHTTPServer docker on the same host as rancher-active-proxy, configured to work with 
- The standalone container's service is reachable from outside directly using `host_ip:8082` in HTTP.
  
rancher-active-proxy configuration  
```yml
rancher-active-proxy:
  ports:
  - 443:443/tcp
  - 80:80/tcp
  environment:
    CRON: 0 2 1 1 *
    DEBUG: 'true'
    DEFAULT_EMAIL: my_personal_email
    DEFAULT_HOST: domain.com
    DEFAULT_PORT: '80'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: adi90x/rancher-active-proxy
  volumes:
  - /opt/rancher-active-proxy/htpasswd:/etc/nginx/htpasswd
  - /opt/rancher-active-proxy/vhost.d:/etc/nginx/vhost.d
  - /opt/rancher-active-proxy/letsencrypt:/etc/letsencrypt
  stdin_open: true
```
SimpleHTTPServer configuration
```yml
test-http:
  image: trinitronx/python-simplehttpserver
  ports:
  - 8082:8080/tcp
  labels:
    rap.port: 8082
    rap.le_test: true
    rap.le_host: sub.domain.com
    rap.host: sub.domain.com
  volumes:
  - /tmp:/var/www:ro
```
**Errors encountered**  
Using logs from the rancher-active-server docker  
```
nginx.1     | 2017/01/05 17:16:12 [error] 124#124: *42 connect() failed (111: Connection refused) while connecting to upstream, client: [my_personal_ip], server: sub.domain.com, request: "GET / HTTP/2.0", upstream: "http://10.42.207.219:8082/", host: "sub.domain.com"
nginx.1     | 2017/01/05 17:16:12 [warn] 124#124: *42 upstream server temporarily disabled while connecting to upstream, client: [my_personal_ip], server: sub.domain.com, request: "GET / HTTP/2.0", upstream: "http://10.42.207.219:8082/", host: "sub.domain.com"
nginx.1     | 2017/01/05 17:16:12 [error] 124#124: *42 no live upstreams while connecting to upstream, client: [my_personal_ip], server: sub.domain.com, request: "GET / HTTP/2.0", upstream: "http://sub.domain.com/", host: "sub.domain.com"
```     
  
In firefox    
502 Bad Gateway  
  
As far as I understand, `rancher-active-server` tries to reach the other service using the internal `docker container ip` of the target, but **cannot reach it**.   
  
Have you got any idea why am I getting that ?  
  
Thank you for your help !

**Comment by adi90x** [comment]
Hello,
First thanks you for using RAP and reporting an issue ! 
Just a few question : 
- Why do you run rancher version 1.1.4 instead of 1.2 or even 1.3 ? 
This project has been started because rancher 1.2 break some networking stuff, while jwilder/nginx-proxy used to work for 1.1.4.
Another point : Is it working if you create a service instead of a standalone container ? 
Can you upload the `/etc/nginx/conf.d/default.conf` file created by rancher active proxy ? 
Just to check if it is a Rancher Network problem, or an API problem.

Regards,
Anyway, I will setup a rancher 1.1.4 environment tonight and try to reproduce the problem !

**Comment by guigouz** [comment]
Hello, rap.port should be 8080 not 8082.

**Comment by adi90x** [comment]
@guigouz : Didn't see that ! It's been a long day ! :)
@ogdabou : rap.port should be the container exposed port ! So I think guigouz is right , probably just a mistake !

**Comment by ogdabou** [comment]
So much help while i have not even reach my sweet home. Thank you.


- Why am I not using 1.2/1.3?
Well, rancher 1.2 included some network issues and I could not afford to fix them for the moment.
- is it working with a service ?
If you mean a container from a stack, yes I did for the exact same result.

The wrong port....  
I will try this asap (tomorrow morning the later) ans report here ! I did not understand the 'expose port' the right way !

**Comment by adi90x** [comment]
I think @guigouz is right , just need to put the correct port and it will work out of the box !
In fact, exposed port is the port of the container that you want to have acces through rancher active proxy, and not the port exposed to the host.
You don't even need to map the container port to a port on the host, just need the container to expose a port ( directive EXPOSE in the dockerfile ).
Waiting for your report before closing the issue !

**Comment by ValentinOdier** [comment]
Hi, 

I'm working with @ogdabou \o/. The issue we had is the following :

I want to access domainx.ext -> cannot resolve (it should). Do it 5 min later it works ... 5min later it cannot resolve again.

Some domain are not available (not all the time). Not all domain are affected. It's a bit wierd. We have seen some issues about it on github, looks like we are not the only one having issues with network in rancher 1.2

We might try again at some point but for now 1.1 will do the job :)

**Comment by ogdabou** [comment]
I'm back and.. It's working now !
I can reach my server, removed the "8082:8080", and htts working with the test letsencrypt env. 
SimpleHTTPServer docker-compose.yml simple example, if you want it
```
test-http:
  labels:
    rap.le_test: 'true'
    rap.le_host: sub.domain.com
    rap.host: sub.domain.com
    rap.port: '8080'
  image: trinitronx/python-simplehttpserver
  volumes:
  - /tmp:/var/www:ro
```

Simply awesome.
Thank you !
