### ISSUE TITLE
Proxy external service

### ISSUE THREAD

**Issue by iBobik** [adi90x/rancher-active-proxy#38]
We also have some legacy server where some service is running, so we want to proxy traffic there with HTTPS termination and certificate generation.

Rancher's load balancer supports proxying to external service with just IP and port specified.

Workaround by another proxying service:
```
  proxy-avexsteeleu:
    image: mikesplain/nginx-proxy-pass
    environment:
      TARGET_SERVER: 192.168.12.3:80
    labels:
      rap.host: example.com
```
https://hub.docker.com/r/mikesplain/nginx-proxy-pass/

Also custom server configuration should be able to do it by setting own Proxy-pass.
