### ISSUE TITLE
Can't create certificate for one of two subdomains

### ISSUE THREAD

**Issue by dj-hedgehog** [adi90x/rancher-active-proxy#4]
I switched from jwilder's nginx-proxy to rap when I migrated from Rancher 1.1.3 to 1.3
All is working good but GitLab's container registry (I also have other services with 2-3 hostnames and certifcates created for them, these work perfectly).

These are the labels of the GitLab stack:

```
labels:
      rap.port: '80'
      rap.le_host: registry.storyx.company,git.storyx.company
      io.rancher.sidekicks: gitlab-data
      io.rancher.container.pull_image: always
      rap.host: registry.storyx.company,git.storyx.company
```

When I execute `/app/letsencrypt.sh` manually inside the container I get:

```
Creating/renewal registry.storyx.company certificates... (registry.storyx.company)
Failed authorization procedure. registry.storyx.company (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://registry.storyx.company/.well-known/acme-challenge/OPQh9Pl-OycWwgC3MYa7b2mH1YJMDVBVsc5nnkvEoTE [85.25.1.223]: 404

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: registry.storyx.company
   Type:   unauthorized
   Detail: Invalid response from
   http://registry.storyx.company/.well-known/acme-challenge/OPQh9Pl-OycWwgC3MYa7b2mH1YJMDVBVsc5nnkvEoTE
   [85.25.1.223]: 404

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

Using Acme server https://acme-v01.api.letsencrypt.org/directory
```
